- name: Ensure rustup-init is available
  homebrew: name=rustup-init state=present

- name: Ensure rustup is installed with rustup-init
  become: yes
  command: rustup-init -y --no-modify-path
  args:
    creates: "{{ home }}/.cargo/bin/rustup"
  environment:
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"
    RUSTUP_INIT_SKIP_PATH_CHECK: "yes"

- name: Ensure a rust toolchain is installed
  become: yes
  command: "{{ home }}/.cargo/bin/rustup install stable"
  args:
    creates: "{{ home }}/.rustup/toolchains/stable-x86_64-apple-darwin"
  environment:
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"

- name: Set the default rust toolchain
  become: yes
  command: "{{ home }}/.cargo/bin/rustup default stable"
  changed_when: false
  environment:
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"

- name: Ensure rust source code has been downloaded
  become: yes
  command: "{{ home }}/.cargo/bin/rustup component add rust-src"
  args:
    creates: "{{ home }}/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/"
  environment:
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"

- name: Initialize bash completion for rust
  become: yes
  shell: "{{ home }}/.cargo/bin/rustup completions bash > {{ home }}/.bash_completion.d/rust_completion.bash"
  args:
    creates: "{{ home }}/.bash_completion.d/rust_completion.bash"
  environment:
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"
