homebrew_packages:
  - cmake
  - bear
  - cgdb
  - clang-format
  - cling
  - doxygen
  - dwarfutils
  - gcc
  - gdb
  - graphviz
  - ninja
  - sdl2
  - sdl2_image
  - sdl2_mixer
  - sdl2_ttf
  - swig
  - tbb
