- name: Dotfiles configuration
  hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env','USER') }}"
    home: "{{ lookup('env','HOME') }}"
  tasks:
    - name: Ensure the dotfiles repo is cloned
      git:
        repo: https://github.com/Emigre/dotfiles.git
        version: master
        dest: "{{ home }}/dotfiles"
        update: no
        accept_hostkey: yes

    - name: Symlink the dotfiles
      file:
        src: "{{ item }}"
        dest: "{{ home }}/{{ item | basename }}"
        state: link
      with_fileglob:
        - files/.*

    - name: Ensure the code folder exists and has the right permissions
      file: "path={{ home }}/code state=directory mode=0755 owner={{ user }}"
      become: yes
      become_user: "{{ user }}"

    - name: Ensure the .local folder exists and has the right permissions
      file: "path={{ home }}/.local state=directory mode=0755 owner={{ user }}"
      become: yes
      become_user: "{{ user }}"

    - name: Ensure the .config folder exists and has the right permissions
      file: "path={{ home }}/.config state=directory mode=0755 owner={{ user }}"
      become: yes
      become_user: "{{ user }}"
