- name: Ensure the .npmrc config file exists
  file: "path={{ home }}/.npmrc state=touch mode=0644 owner={{ user }}"
  sudo: yes
  when: is_home

- name: Ensure .npmrc has ~/.node as the global items location
  lineinfile: dest={{ home }}/.npmrc regexp="^prefix"  line="prefix={{ home }}/.node"
  when: is_home

- name: Ensure several node folders exist and have the right permissions
  file: "path={{ home }}/{{ item }} state=directory mode=0755 owner={{ user }}"
  sudo: yes
  with_items:
    - .npm
    - .node/bin
    - .node/lib
    - .node/lib/node_modules
  when: is_home

- name: Ensure configured global node packages are installed
  npm: "name={{ item }} path={{ home }}/.node/lib"
  with_items: "{{ (node_packages.common + node_packages.work) if is_work|bool else (node_packages.common + node_packages.home) if is_home|bool else node_packages.common }}"
