- name: Ensure there is a Vagrant folder
  file: "path=/Users/{{ user }}/Vagrant state=directory mode=0755 owner={{ user }}"
  sudo: yes

- name: Ensure Vagrant has the folders it needs for its Vagrantfiles
  file: "path=/Users/{{ user }}/Vagrant/{{ item }} state=directory mode=0755 owner={{ user }}"
  sudo: yes
  with_items:
    - ubuntu-1404-desktop
    - win7-ie10
    - win7-ie8
    - win7-ie9
    - win81-ie11

- name: Symlink the IE8 Vagrant file
  file:
    src: "{{ item }}"
    dest: "/Users/{{ user }}/Vagrant/win7-ie8/Vagrantfile"
    state: link
  with_fileglob:
    - ./win7-ie8/Vagrantfile

- name: Symlink the IE9 Vagrant file
  file:
    src: "{{ item }}"
    dest: "/Users/{{ user }}/Vagrant/win7-ie9/Vagrantfile"
    state: link
  with_fileglob:
    - ./win7-ie9/Vagrantfile

- name: Symlink the IE10 Vagrant file
  file:
    src: "{{ item }}"
    dest: "/Users/{{ user }}/Vagrant/win7-ie10/Vagrantfile"
    state: link
  with_fileglob:
    - ./win7-ie10/Vagrantfile

- name: Symlink the IE11 Vagrant file
  file:
    src: "{{ item }}"
    dest: "/Users/{{ user }}/Vagrant/win81-ie11/Vagrantfile"
    state: link
  with_fileglob:
    - ./win81-ie11/Vagrantfile

- name: Symlink the Ubuntu TrustyTahr with desktop Vagrant file
  file:
    src: "{{ item }}"
    dest: "/Users/{{ user }}/Vagrant/ubuntu-1404-desktop/Vagrantfile"
    state: link
  with_fileglob:
    - ./ubuntu-1404-desktop/Vagrantfile
