- name: Ensure the dotfiles folder exists and has the right permissions
  file: "path={{ home }}/Dropbox/dotfiles state=directory mode=0755 owner={{ user }}"
  become: yes

- name: Ensure there is a symlink to the dotfiles folder in the home folder
  file:
    src: "{{ home }}/Dropbox/dotfiles"
    dest: "{{ home }}/dotfiles"
    state: link

- name: Ensure the code folder exists and has the right permissions
  file: "path={{ home }}/code state=directory mode=0755 owner={{ user }}"
  become: yes

- name: Ensure there is a vagrant folder
  file: "path={{ home }}/vagrant state=directory mode=0755 owner={{ user }}"
  become: yes

- name: Ensure the vagrant repo is cloned
  git:
    repo: https://github.com/Emigre/vagrant.git
    version: master
    dest: "{{ home }}/vagrant"
    update: yes
    accept_hostkey: yes
  when: is_home

- name: Ensure there is a scripts folder
  file: "path={{ home }}/Dropbox/scripts state=directory mode=0755 owner={{ user }}"
  become: yes

- name: Ensure the scripts repo is cloned
  git:
    repo: https://github.com/Emigre/scripts.git
    version: master
    dest: "{{ home }}/Dropbox/scripts"
    update: yes
    accept_hostkey: yes

- name: Ensure there is a symlink to the scripts folder in the home folder
  file:
    src: "{{ home }}/Dropbox/scripts"
    dest: "{{ home }}/scripts"
    state: link

- name: Ensure there is a bash completions folder
  file: "path={{ home }}/.bash_completion.d state=directory mode=0755 owner={{ user }}"
  become: yes

- name: Ensure the git completion is symlinked into the bash completion folder
  file:
    src: "{{ home }}/Dropbox/scripts/git_completion.bash"
    dest: "{{ home }}/.bash_completion.d/git.bash"
    state: link

- name: Symlink the dotfiles
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./.*

- name: Set the .gituser file
  template:
    src: "gituser.j2"
    dest: "{{ home }}/.gituser"
    group: admin
    mode: 0664
