- name: Ensure the C++ homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ (homebrew_packages.common + homebrew_packages.home) if is_home|bool else homebrew_packages.common }}"

- name: Ensure llvm is installed
  homebrew: name=llvm state=present install_options=with-toolchain
  when: is_home

- name: Ensure the depot tools are cloned
  git:
    repo: https://chromium.googlesource.com/chromium/tools/depot_tools.git
    version: master
    dest: "{{ home }}/depot_tools"
    update: no
    accept_hostkey: yes
  when: is_home

- name: Symlink the C++ dotfiles
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  become: yes
  become_user: "{{ user }}"
  with_fileglob:
    - ".*"
  when: is_home

- name: Symlink the debugger python scripts to Python 2.7 site-packages
  file:
    src: "{{ item }}"
    dest: "/Library/Python/2.7/site-packages/{{ item | basename }}"
    state: link
  become: yes
  become_user: "{{ user }}"
  with_fileglob:
    - "*dbinit.py"
  when: is_home

- name: Ensure xcpretty is installed for Objective-C
  gem: name=xcpretty state=present
