# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  puts "\nNOTE: After the box boots, your app will be available at e.g. http://192.168.50.1:8080"
  puts "      If Vagrant won't detect the machine state, just Ctrl + C after the GUI is up\n\n"

  config.vm.box = "Windows 7 with IE10 (32bit)"
  config.vm.box_url = "http://aka.ms/vagrant-win7-ie10"

  # Makes the host machine available as "192.168.50.1" on the guest
  config.vm.network "private_network", ip: "192.168.50.2"

  # http://stackoverflow.com/questions/23574387/why-is-vagrant-trying-to-ssh-to-windows-guest
  # https://www.vagrantup.com/blog/feature-preview-vagrant-1-6-windows.html
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.customize ["setextradata", :id, "global", "GUI/MaxGuestResolution any"]
    vb.customize ["setextradata", :id, "\"Win8\" \"CustomVideoMode1\" \"1920x1200x32\""]
  end

end
