- name: Ensure Python is installed
  homebrew: name=python state=present

- name: Ensure Pypenv is installed
  homebrew: name=pipenv state=present

- name: Ensure configured python packages are installed
  pip: "executable=pip3 state=present name={{ item }}"
  with_items: "{{ (python_packages.common + python_packages.home) if is_home|bool else python_packages.common }}"

- name: Ensure the Python language server is installed
  homebrew: "name={{ item }} state=present"
  with_items:
    - jedi
    - python-language-server

- name: Ensure python packages related to C++ are installed
  pip: "executable=pip3 state=present name={{ item }}"
  with_items: "{{ cpp_python_packages }}"
  when: is_home
