python_packages:
  - autopep8
  - flake8
  - http-prompt
  - neovim
  - pylint
  - virtualenv
  - ipdb
  - mypy
  - pudb
  - pyinstaller

cpp_python_packages:
  - cpplint
  - compdb
  - gdbgui
  - scan-build
