python_packages:
  common:
    - autopep8
    - compdb
    - flake8
    - http-prompt
    - pylint
    - virtualenv
  home:
    - cpplint
    - gdbgui
    - ipdb
    - mypy
    - pudb
    - pyinstaller
