- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ (homebrew_taps.common + homebrew_taps.home) if is_home|bool else homebrew_taps.common }}"

- name: Ensure Java is installed with homebrew cask
  homebrew_cask: "name=java"

- name: Ensure the homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ (homebrew_packages.common + homebrew_packages.home) if is_home|bool else homebrew_packages.common }}"

- name: Upgrade all homebrew packages (if configured)
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade

- name: Ensure the homebrew cask applications are installed
  homebrew_cask: "name={{ item }}"
  with_items: "{{ (homebrew_cask_apps.common + homebrew_cask_apps.home) if is_home|bool else homebrew_cask_apps.common }}"
