- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps.common }}"

- name: Ensure the homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ (homebrew_packages.common + homebrew_packages.home) if is_home|bool else homebrew_packages.common }}"

- name: Ensure servers are installed with homebrew
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_packages_servers
  when: is_home

- name: Ensure databases are installed with homebrew
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_packages_databases
  when: is_home

- name: Ensure games are installed with homebrew
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_packages_games
  when: is_home

- name: Upgrade all homebrew packages (if configured)
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade

- name: Ensure the homebrew cask applications are installed
  homebrew_cask: "name={{ item }}"
  with_items: "{{ (homebrew_cask_apps.common + homebrew_cask_apps.home) if is_home|bool else homebrew_cask_apps.common }}"
