- name: Ensure homebrew is installed
  git:
    repo: git://github.com/Homebrew/homebrew.git
    version: master
    dest: "/usr/local"
    update: no
    accept_hostkey: yes

# Tap
- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ (homebrew_taps.common + homebrew_taps.home) if home|bool else homebrew_taps.common }}"

# Brew
- name: Ensure configured homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ (homebrew_packages.common + homebrew_packages.home) if home|bool else homebrew_packages.common }}"

- name: Upgrade all homebrew packages (if configured)
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade

# Cask
- name: Ensure configured homebrew cask applications are installed
  homebrew_cask: "name={{ item }}"
  with_items: "{{ (homebrew_cask_apps.common + homebrew_cask_apps.work) if work|bool else (homebrew_cask_apps.common + homebrew_cask_apps.home) if home|bool else homebrew_cask_apps.common }}"
