- name: Ensure Node.js is installed with homebrew
  homebrew: name=node state=present

- name: Ensure the JavaScript homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew_packages }}"

- name: Ensure the .npmrc config file exists
  file: "path={{ home }}/.npmrc state=touch mode=0644 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Ensure .npmrc has ~/.node as the global items location
  lineinfile: dest={{ home }}/.npmrc regexp="^prefix"  line="prefix={{ home }}/.node"

- name: Ensure several node folders exist and have the right permissions
  file: "path={{ home }}/{{ item }} state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - .npm
    - .node/bin
    - .node/lib
    - .node/lib/node_modules

- name: Ensure eslint is installed globally
  npm: "name={{ item }} state=present global=yes"
  with_items:
    - eslint
    - babel-eslint
    - eslint-config-airbnb
    - eslint-plugin-babel
    - eslint-plugin-import
    - eslint-plugin-react
    - eslint-plugin-jsx-a11y
  changed_when: false

- name: Ensure configured global node packages are installed
  npm: "name={{ item }} state=present global=yes"
  with_items: "{{ (node_packages.common + node_packages.home) if is_home|bool else (node_packages.common + node_packages.work) }}"
