- name: Ensure Go is installed with homebrew
  homebrew: name=go state=present

- name: Ensure golint is installed
  shell: /usr/local/bin/go get -u golang.org/x/lint/golint
  become: yes
  become_user: "{{ user }}"
  args:
    creates: "{{ home }}/code/go/bin/golint"
  environment:
    GOPATH: "{{ home }}/code/go"
  changed_when: false

- name: Ensure the Go language server is installed
  shell: /usr/local/bin/go get -u github.com/sourcegraph/go-langserver
  become: yes
  become_user: "{{ user }}"
  args:
    creates: "{{ home }}/code/go/bin/go-langserver"
  environment:
    GOPATH: "{{ home }}/code/go"
  changed_when: false
