- name: Ensure Go is installed with homebrew
  homebrew: name=go state=present

- name: Ensure the Go workspace exists and has the right permissions
  file: "path={{ home }}/code/go state=directory mode=0755 owner={{ user }}"
  become: yes
