- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Ensure the homebrew packages are installed
  homebrew:
    name: ["{{ item }}"]
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Ensure the homebrew cask applications are installed
  homebrew_cask:
    name: ["{{ item }}"]
  with_items: "{{ homebrew_cask_apps }}"

- name: Ensure the navi repo is cloned
  git:
    repo: https://github.com/Emigre/navi.git
    version: master
    dest: "{{ home }}/navi"
    update: no
    accept_hostkey: yes

# Neovim

- name: Ensure the .config folder exists and has the right permissions
  file: "path={{ home }}/.config state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Ensure the .vim folder exists and has the right permissions
  file: "path={{ home }}/.vim state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Ensure the neovim config folder is a symlink to the vim config folder
  file:
    src: "{{ home }}/.vim"
    dest: "{{ home }}/.config/nvim"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure the subfolders inside .vim exist and have the right permissions
  file: "path={{ home }}/.vim/{{ item }} state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - autoload
    - backups
    - colors
    - plugged
    - plugin
    - swaps
    - undo

- name: Symlink init.vim
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/{{ item | basename }}"
    state: link
  with_fileglob:
    - "init.vim"

- name: Symlink plug.vim
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/autoload/{{ item | basename }}"
    state: link
  with_fileglob:
    - "plug.vim"

- name: Symlink the vim color scheme
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/colors/{{ item | basename }}"
    state: link
  with_fileglob:
    - "zenburn.vim"

- name: Ensure .vimrc is a symlink to init.vim
  file:
    src: "{{ home }}/.vim/init.vim"
    dest: "{{ home }}/.vimrc"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure Neovim is installed
  homebrew: name=nvim state=present