- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Ensure the homebrew packages are installed
  homebrew:
    name: ["{{ item }}"]
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Ensure the homebrew cask applications are installed
  homebrew_cask:
    name: ["{{ item }}"]
  with_items: "{{ homebrew_cask_apps }}"

# Neovim installed via https://github.com/Emigre/vim.git
