# Neovim installed via https://github.com/Emigre/vim.git

- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Ensure the homebrew packages are installed
  homebrew:
    name: ["{{ item }}"]
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Ensure the homebrew cask applications are installed
  homebrew_cask:
    name: ["{{ item }}"]
  with_items: "{{ homebrew_cask_apps }}"

- name: Ensure Node.js is installed with homebrew
  homebrew: name=node state=present

- name: Ensure configured global node packages are installed
  npm: "name={{ item }} state=present global=yes"
  with_items: "{{ node_packages }}"

- name: Ensure Python is installed
  homebrew: name=python state=present
