- name: Ensure configured taps are tapped
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Ensure the homebrew packages are installed
  homebrew:
    name: ["{{ item }}"]
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Ensure servers are installed with homebrew
  homebrew: 
    name: ["{{ item }}"]
    state: present
  with_items: "{{ homebrew_packages_servers }}"
  when: is_home

- name: Ensure databases are installed with homebrew
  homebrew:
    name: ["{{ item }}"] 
    state: present
  with_items: "{{ homebrew_packages_databases }}"
  when: is_home

- name: Ensure games are installed with homebrew
  homebrew:
    name: ["{{ item }}"] 
    state: present
  with_items: "{{ homebrew_packages_games }}"
  when: is_home

- name: Ensure the homebrew cask applications are installed
  homebrew_cask:
    name: ["{{ item }}"]
  with_items: "{{ homebrew_cask_apps }}"

- name: Ensure the homebrew cask applications for home are installed
  homebrew_cask:
    name: ["{{ item }}"]
  with_items: "{{ homebrew_cask_apps_home }}"

# mutt
# ----

- name: Ensure the joplin config folder exists
  file: "path={{ home }}/.mutt state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Symlink mutt config files
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  with_fileglob:
    - ".muttrc"
    - "*.muttrc"
    - "mailcap"

# weechat
# -------

# TODO configure weechat

# joplin
# ------

- name: Ensure the joplin config folder exists
  file: "path={{ home }}/.config/joplin state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Symlink the joplin keymap file
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.config/joplin/{{ item | basename }}"
    state: link
  with_fileglob:
    - keymap.json

# apart from the keymap joplin stores its data and config
# info in the sqlite file inside ~/.config/joplin
