- name: Ensure the Haskell homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: homebrew_packages

- name: Ensure the yesod cli is installed
  command: stack install yesod-bin
