- name: Ensure Haskell is installed
  homebrew: name=ghc state=present

- name: Ensure the Haskell homebrew packages are installed
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew_packages }}"
  
# - name: Ensure the haskell language server project is cloned
#   # to build:
#   # stack ./install.hs hie-8.6.5
#   git:
#     repo: git@github.com:haskell/haskell-ide-engine.git
#     version: master
#     dest: "{{ home }}/hie"
#     update: no
#     accept_hostkey: yes
