- name: Ensure proper permissions in /usr/local
  file:
    path: "/usr/local"
    group: admin
    mode: 0775
    state: directory
  sudo: yes

- name: Ensure proper permissions in /usr/local/bin
  file:
    path: "/usr/local/bin"
    group: admin
    mode: 0775
    state: directory
    recurse: true
  sudo: yes

- name: Ensure the Code folder exists and has the right permissions
  file: "path=~/Code state=directory mode=0755 owner={{ user }}"
  sudo: yes
