- name: Ensure vim is installed with homebrew
  homebrew: name=vim state=present

- name: Symlink .vimrc
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  become: yes
  become_user: "{{ user }}"
  with_fileglob:
    - ".vimrc"

- name: Ensure all needed vim folders exist and have the right permissions
  file: "path={{ home }}/{{ item }} state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - .vim
    - .vim/autoload
    - .vim/backups
    - .vim/bundle
    - .vim/colors
    - .vim/plugin
    - .vim/plugged
    - .vim/swaps
    - .vim/undo

- name: Ensure vim-plug is downloaded in the autoload folder
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.vim/autoload/plug.vim"

- name: Symlink the configuration files for the vim plugins
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/plugin/{{ item | basename }}"
    state: link
  with_fileglob:
    - "*.vim"

- name: Ensure the vim plugins are cloned in the plugged folder
  git:
    repo: "https://github.com/{{ item }}.git"
    version: master
    dest: "{{ home }}/.vim/plugged/{{ item | regex_search('\\/.+$') }}"
    update: no
    accept_hostkey: yes
  with_items:
    - vim-scripts/Zenburn
    - vermeulen/vim-easyclip
    - tpope/vim-repeat
    - kien/ctrlp.vim
    - Shougo/unite.vim
    - Shougo/vimfiler.vim
    - Shougo/vinarise.vim
    - ap/vim-buftabline
    - jlanzarotta/bufexplorer
    - Yggdroot/indentLine
    - airblade/vim-gitgutter
    - tpope/vim-fugitive
    - tommcdo/vim-fugitive-blame-ext
    - editorconfig/editorconfig-vim
    - scrooloose/nerdcommenter
    - terryma/vim-multiple-cursors
    - w0rp/ale
    - rhysd/vim-clang-format
    - autozimu/LanguageClient-neovim
    - junegunn/fzf
    - roxma/vim-hug-neovim-rpc
    - roxma/nvim-yarp
    - ncm2/ncm2
    - pangloss/vim-javascript
    - mxw/vim-jsx
    - leafgarland/typescript-vim
    - drmikehenry/vim-headerguard
    - bfrg/vim-cpp-modern
    - Vimjas/vim-python-pep8-indent
    - elzr/vim-json
    - plasticboy/vim-markdown

- name: Ensure the language server plugin is cloned in the plugged folder
  git:
    repo: https://github.com/autozimu/LanguageClient-neovim.git
    version: next
    dest: "{{ home }}/.vim/plugged/autozimu/LanguageClient-neovim"
    update: no
    accept_hostkey: yes

- name: Compile the language server plugin
  become: yes
  become_user: "{{ user }}"
  command: bash ./install.sh
  args:
    chdir: "{{ home }}/.vim/plugged/LanguageClient-neovim"
    creates: "{{ home }}/.vim/plugged/LanguageClient-neovim/bin/languageclient"
