- name: Symlink .vimrc
  file:
    src: "{{ item }}"
    dest: "{{ home }}/{{ item | basename }}"
    state: link
  become: yes
  become_user: "{{ user }}"
  with_fileglob:
    - ".vimrc"

- name: Ensure all needed vim folders exist and have the right permissions
  file: "path={{ home }}/{{ item }} state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - .vim
    - .vim/autoload
    - .vim/backups
    - .vim/bundle
    - .vim/colors
    - .vim/plugin
    - .vim/plugged
    - .vim/swaps
    - .vim/undo

- name: Ensure vim-plug is downloaded in the autoload folder
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.vim/autoload/plug.vim"

- name: Symlink the configuration files for the vim plugins
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/plugin/{{ item | basename }}"
    state: link
  with_fileglob:
    - "*.vim"

- name: Ensure the vim plugins are cloned in the plugged folder
  git:
    repo: "https://github.com/{{ item }}.git"
    version: master
    dest: "{{ home }}/.vim/plugged/{{ item | regex_search('\\/.+$') }}"
    update: no
    accept_hostkey: yes
  with_items:
    - airblade/vim-gitgutter
    - ap/vim-buftabline
    - bfrg/vim-cpp-modern
    - editorconfig/editorconfig-vim
    - jlanzarotta/bufexplorer
    - kien/ctrlp.vim
    - scrooloose/nerdcommenter
    - Shougo/unite.vim
    - Shougo/vimfiler.vim
    - Shougo/vinarise.vim
    - svermeulen/vim-easyclip
    - terryma/vim-multiple-cursors
    - tommcdo/vim-fugitive-blame-ext
    - tpope/vim-fugitive
    - tpope/vim-repeat
    - vim-scripts/Zenburn
    - Yggdroot/indentLine
    - elzr/vim-json
    - leafgarland/typescript-vim
    - mxw/vim-jsx
    - pangloss/vim-javascript
    - plasticboy/vim-markdown
    - Vimjas/vim-python-pep8-indent
    - w0rp/ale

- name: Clone YouCompleteMe
  git:
    repo: "https://github.com/Valloric/YouCompleteMe.git"
    version: master
    dest: "{{ home }}/.vim/plugged/YouCompleteMe"
    update: no
    accept_hostkey: yes

- name: Compile YouCompleteMe
  become: yes
  become_user: "{{ user }}"
  command: python3 ./install.py --clang-completer --java-completer --rust-completer
  args:
    chdir: "{{ home }}/.vim/plugged/YouCompleteMe"
    creates: "{{ home }}/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so"
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/sbin:{{ home }}/.cargo/bin"
    RUSTUP_HOME: "{{ home }}/.rustup"
    CARGO_HOME: "{{ home }}/.cargo"
