- name: Ensure the config folder exists and has the right permissions
  file: "path={{ home }}/.config state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Ensure the vim repo is cloned
  git:
    repo: https://github.com/Emigre/vim.git
    version: master
    dest: "{{ home }}/vim"
    update: no
    accept_hostkey: yes

- name: Ensure the subfolders inside the vim configuration folder exist and have the right permissions
  file: "path={{ home }}/vim/{{ item }} state=directory mode=0755 owner={{ user }}"
  become: yes
  become_user: "{{ user }}"
  with_items:
    - backups
    - undo
    - swaps
    - plugged

- name: Ensure the .vim config folder is a symlink to the vim config folder
  file:
    src: "{{ home }}/vim"
    dest: "{{ home }}/.vim"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure .vimrc is a symlink to init.vim
  file:
    src: "{{ home }}/vim/init.vim"
    dest: "{{ home }}/.vimrc"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure the neovim config folder is a symlink to the vim config folder
  file:
    src: "{{ home }}/vim"
    dest: "{{ home }}/.config/nvim"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure the coc config folder is a symlink to the coc config folder inside the vim repo
  file:
    src: "{{ home }}/vim/coc"
    dest: "{{ home }}/.config/coc"
    state: link
  become: yes
  become_user: "{{ user }}"

- name: Ensure vim is installed
  homebrew:
    name: vim
    state: present

- name: Ensure neovim is installed
  homebrew:
    name: nvim
    state: present
