- name: Ensure all needed vim folders exist and have the right permissions
  file: "path={{ home }}/{{ item }} state=directory mode=0755 owner={{ user }}"
  sudo: yes
  with_items:
    - .vim
    - .vim/backups
    - .vim/bundle
    - .vim/colors
    - .vim/plugin
    - .vim/swaps
    - .vim/undo

- name: Ensure vundle is cloned in the bundle folder
  git:
    repo: git://github.com/VundleVim/Vundle.vim.git
    version: master
    dest: "{{ home }}/.vim/bundle/Vundle.vim"
    update: no
    accept_hostkey: yes

- name: Ensure my vim snippets are cloned in the bundle folder
  git:
    repo: git://github.com/Emigre/vim-snippets.git
    version: master
    dest: "{{ home }}/.vim/bundle/vim-snippets"
    update: no
    accept_hostkey: yes

- name: Symlink the configuration files for all installed vim plugins
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.vim/plugin/{{ item | basename }}"
    state: link
  with_fileglob:
    - ./*.vim
