- name: Ensure iTerm2 is installed with homebrew cask
  homebrew_cask: name=iterm2 state=present

- name: Symlink the iTerm2 preferences
  file:
    src: "{{ home }}/dotfiles/roles/iterm/preferences"
    dest: "{{ home }}/.iterm.d"
    state: link

- name: Ensure the iTerm profiles folder exists and has the right permissions
  file:
    path: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/"
    state: directory
    mode: 0755
    owner: "{{ user }}"
  become: yes

- name: Symlink iTerm2 profiles
  file:
    src: "{{ item }}"
    dest: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/{{ item | basename }}"
    state: link
  with_fileglob:
    - "*.json"
