- name: Ensure iTerm2 is installed with homebrew cask
  homebrew_cask: name=iterm2 state=present

- name: Ensure the iTerm profiles folder exists and has the right permissions
  file:
    path: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/"
    state: directory
    mode: 0755
    owner: "{{ user }}"
  become: yes
  become_user: "{{ user }}"

# The profile settings are saved automatically
- name: Symlink iTerm2 profiles
  file:
    src: "{{ item }}"
    dest: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/{{ item | basename }}"
    state: link
    follow: False
  with_fileglob:
    - "*.json"

- name: Ensure an iTerm preferences folder exists and has the right permissions
  file:
    path: "{{ home }}/.iterm2.d"
    state: directory
    mode: 0755
    owner: "{{ user }}"
  become: yes
  become_user: "{{ user }}"

# Settings are saved when iTerm quits - ensure that 'Load preferences from a custom folder or URL'
# points to {{ home }}/.iterm2.d/
- copy:
    src: com.googlecode.iterm2.plist
    dest: "{{ home }}/.iterm2.d/com.googlecode.iterm2.plist"
    force: no
