- name: Ensure iTerm2 is installed with homebrew cask
  homebrew_cask: name=iterm2 state=present

- name: Ensure the iTerm profiles folder exists and has the right permissions
  file:
    path: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/"
    state: directory
    mode: 0755
    owner: "{{ user }}"
  become: yes

# The profile settings are saved automatically
- name: Symlink iTerm2 profiles
  file:
    src: "{{ item }}"
    dest: "{{ home }}/Library/Application\ Support/iTerm2/DynamicProfiles/{{ item | basename }}"
    state: link
  with_fileglob:
    - "*.json"

# Settings are saved when iTerm quits - ensure that 'Load preferences from a custom folder or URL'
# points to the 'roles/iterm/preferences' folder that contains 'com.googlecode.iterm2.plist'
